import type { Player } from './types';

export const SAVED_PLAYERS: Player[] = [
  { name: 'Bell',        rating: 8,   isGK: false, position: 'MID' },
  { name: 'Ky',          rating: 9,   isGK: false, position: 'MID' },
  { name: 'Jon C',       rating: 7,   isGK: false, position: 'DEF' },
  { name: 'Jord',        rating: 9,   isGK: false, position: 'DEF' },
  { name: 'Callum',      rating: 7,   isGK: false, position: 'DEF' },
  { name: 'OB',          rating: 7,   isGK: false, position: 'MID' },
  { name: 'Matts',       rating: 7,   isGK: false, position: 'MID' },
  { name: 'Kie',         rating: 7,   isGK: false, position: 'DEF' },
  { name: 'Cob',         rating: 7,   isGK: false, position: 'MID' },
  { name: 'Mitch',       rating: 6,   isGK: false, position: 'MID' },
  { name: 'Owen',        rating: 9,   isGK: false, position: 'MID' },
  { name: 'Ant',         rating: 7,   isGK: true,  position: 'ATT' },
  { name: 'Stokes',      rating: 5.5, isGK: true,  position: 'DEF' },
  { name: 'Hannon',      rating: 6.5, isGK: false, position: 'MID' },
  { name: 'Matt Field',  rating: 6,   isGK: false, position: 'ATT' },
  { name: 'J Burke',     rating: 5,   isGK: true,  position: 'DEF' },
  { name: 'K-Don',       rating: 5.5, isGK: false, position: 'MID' },
  { name: 'Smithy',      rating: 6,   isGK: false, position: 'ATT' },
  { name: 'Beaver',      rating: 7,   isGK: false, position: 'DEF' },
  { name: 'Tom Burke',   rating: 7,   isGK: false, position: 'MID' },
  { name: 'Tom Harris',  rating: 7,   isGK: false, position: 'MID' },
  { name: 'Graham',      rating: 6,   isGK: false, position: 'DEF' },
  { name: 'Ed',          rating: 8,   isGK: true,  position: 'GK' },
  { name: 'Ize',         rating: 7,   isGK: false, position: 'MID' },
  { name: 'Belcher',     rating: 5,   isGK: false, position: 'MID' },
  { name: 'Matty D',     rating: 7,   isGK: false, position: 'MID' },
  { name: 'Salter',      rating: 4,   isGK: false, position: 'DEF' },
  { name: 'Hextell',     rating: 8,   isGK: false, position: 'MID' },
  // second Mitch renamed to avoid duplicate keys
  { name: 'Mitch H',     rating: 6.5, isGK: false, position: 'MID' },
  { name: 'Ross',        rating: 7.5, isGK: false, position: 'MID' },
  { name: 'Freddie',     rating: 8,   isGK: false, position: 'ATT' },
];